### ISSUE TITLE
TypeError: Can't set property items of undefined.

### ISSUE THREAD

**Issue by cpouldev** [stape-io/gads-offline-conversion-tag#1]
The tag throws the following error while the `items` variable is already populated

`TypeError: Can't set property items of undefined.`

![image](https://user-images.githubusercontent.com/8311776/204571804-4b58efb0-47b5-489f-96a8-bb802d2a6628.png)

![image](https://user-images.githubusercontent.com/8311776/204572154-41f7e504-135c-4f6a-a68b-be607d49925c.png)

I'm following the guide here https://stape.io/blog/google-ads-offline-conversion-using-server-gtm

Any help on this will be deeply appreciated. Thanks

**Comment by Bukashk0zzz** [comment]
Hi,
Thanks for report.
Issues is fixed https://github.com/stape-io/gads-offline-conversion-tag/commit/2c74ee5b79ee3a4f568658894be5505c46bc2bd1
