### ISSUE TITLE
Store bearer token in template storage

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/gads-offline-conversion-tag#10]
It would simplify the setup process if we did not need firebase to store the oauth bearer token. 

I think it would be more simple to just store it in template storage to share it between requests.

https://developers.google.com/tag-platform/tag-manager/server-side/api#templatedatastorage

If the token is not available just create a new token.

**Comment by Bukashk0zzz** [comment]
We discussed this internally and decided that we would not support this in our tag.

p.s. More features are coming to Stape that will solve the need of this
