### ISSUE TITLE
Falsy customer identifiers attempted to be hashed and set along with uploadClickConversions calls

### ISSUE THREAD

**Issue by Adbroad** [stape-io/gads-offline-conversion-tag#14]
**Description**

[Falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) values in User Data variables causes 'uploadClickConversions' requests to break by adding a faulty ['userIdentifier' object](https://developers.google.com/google-ads/api/rest/reference/rest/v16/UserIdentifier) in the body of the request.

**How to reproduce**

1. Set custom variables in the "User Data" section of the template
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/f588b9ba-0382-44b3-b34f-1dbe9d0949d8)
2. Have at least one of those variables evaluate to _undefined_ or an _empty string_ (please note the behavior differs for both. cases, [see below](#note))
3. Fire a request to the sGTM container to fire the tag and inspect the Google Ads API requests.

NOTE : I haven't tested with letting the template fetch the email/phone automatically from the incoming event data. It's worth checking too.

**Examples**

**Tag configuration**

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/56553805-b871-4676-affe-fa91c2115cbf)

**Incoming request**

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/94f39670-9c5e-4d2c-a437-c5fc910a84c8)

**Variables evaluated values**

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/3f349679-4aa0-43d0-8c37-cd85c46a6e31)

**Resulting Google Ads API request**

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/a344f45e-f04d-45ec-b718-6b910813e56a)

<p id="note"><b>NOTE</b></p>

If one of the variables evaluates to an _empty string_ instead of _undefined_, _null_ or _false_, the resulting request is as follows:

![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/126677705/74f04008-6b13-42e0-a058-b017324862fe)

**Why it's an issue**

Most people will use custom variables to set user data like Email or Phone. However, in some cases, at least one of those may not be sent along with the incoming request for whatever reason (not available in CRM, wrong formatting...), which leads to breaking an otherwise functional conversion upload. After all, having email only is enough according to Google.

**Comment by Bukashk0zzz** [comment]
Hi,

Thanks for pointing us to this issue.
We will fix it.
