### ISSUE TITLE
Bug "gbraid" Parameter Name?

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/gads-offline-conversion-tag#19]
Isn't there a bug in the naming of the "gbraid" Parameter here? https://github.com/stape-io/gads-offline-conversion-tag/blob/main/template.tpl#L806, https://github.com/stape-io/gads-offline-conversion-tag/blob/main/template.tpl#L812 & https://github.com/stape-io/gads-offline-conversion-tag/blob/main/template.tpl#L813

Documentation: https://developers.google.com/google-ads/api/rest/reference/rest/v15/customers/uploadClickConversions

**Comment by kHorozhanov** [comment]
@alexgarciab Thank you so much for reporting this issue
