### ISSUE TITLE
email and phone is not picked from standard Ga4 user_data

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/gads-offline-conversion-tag#7]
It would be nice if the templates would check the event data for standard Ga4 user_data

email: user_data.email
phone: user_data.phone

Just like you do with the facebook conversion API

**Comment by Bukashk0zzz** [comment]
done https://github.com/stape-io/gads-offline-conversion-tag/commit/0f9e4c832e0fdac18455a648c51adc1b6d75bb53
