### ISSUE TITLE
Add the users name and address to the user data

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/gads-offline-conversion-tag#8]
The tag currently only supports email and phone

Please add support for all user data

- first_name
- last_name
- city
- etc..

Link to documentation
https://developers.google.com/google-ads/api/rest/reference/rest/v12/UserIdentifier?hl=en

**Comment by Bukashk0zzz** [comment]
Partly done https://github.com/stape-io/gads-offline-conversion-tag/commit/0f9e4c832e0fdac18455a648c51adc1b6d75bb53

You now can pass addressInfo

**Comment by Larsfriishansen** [comment]
I don't understand how to add address info ?
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/107996813/d23b67ac-59cc-45f9-9b87-9b89493b3cf4)

**Comment by Bukashk0zzz** [comment]
You can use https://tagmanager.google.com/gallery/#/owners/stape-io/templates/object-builder-variable
to build addressInfo object

**Comment by Larsfriishansen** [comment]
I just tried adding address info:
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/107996813/69952ae3-7fcb-4375-a3e2-de19a4521deb)

Using this object variable
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/107996813/ef2fe050-014e-441a-8ac6-22d1a9ada2b8)

Variable
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/107996813/bb7a5ce6-a7b4-43a1-83de-0a8475fb7cd1)

This gives me the following error: "TypeError: Object has no 'map' property."
