### ISSUE TITLE
More detailed help text about cart data

### ISSUE THREAD

**Issue by Larsfriishansen** [stape-io/gads-offline-conversion-tag#9]
Please add more detailed help text
![image](https://github.com/stape-io/gads-offline-conversion-tag/assets/107996813/2556ccb0-443a-4579-a044-48a5c8cf657f)

Link to google documentation
https://developers.google.com/google-ads/api/docs/conversions/upload-clicks#include_cart_data_in_conversions

1. merchant_id: The ID of the associated [Merchant Center](https://support.google.com/google-ads/answer/188493) account.
2. feed_country_code: The ISO 3166 two-character region code of the Merchant Center feed.
3. feed_language_code: The ISO 639-1 language code of the Merchant Center feed.

**Comment by Bukashk0zzz** [comment]
Done https://github.com/stape-io/gads-offline-conversion-tag/commit/0f9e4c832e0fdac18455a648c51adc1b6d75bb53
